name: shuttle_tracker_backend
description: The backend for the Shuttle Tracker application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  postgres: ^2.6.1
  firebase_admin: ^0.2.0
  jaguar_jwt: ^3.0.0
  crypto: ^3.0.3
  shelf_web_socket: ^1.0.0
