import 'User.dart';

class FeedbackModel {
  final String feedbackId; // auto-generated by backend
  User user;
  String comments;
  int rating; // 1 to 5
  DateTime createdAt;

  FeedbackModel({
    required this.feedbackId,
    required this.user,
    required this.comments,
    required this.rating,
    DateTime? createdAt,
  }) : createdAt = createdAt ?? DateTime.now();

  // JSON serialization/deserialization
  factory FeedbackModel.fromJson(Map<String, dynamic> json) {
    return FeedbackModel(
      feedbackId: json['feedbackId'].toString(),
      user: User.fromJson(json['user']),
      comments: json['comments'],
      rating: json['rating'],
      createdAt: DateTime.parse(json['createdAt']),
    );
  }

  Map<String, dynamic> toJson() => {
    'feedbackId': feedbackId,
    'user': user.toJson(),
    'comments': comments,
    'rating': rating,
    'createdAt': createdAt.toIso8601String(),
  };
}
